import java.io.IOException;


import server.HttpServer;
import utils.AppConfig;
import utils.RouterConfig;
import router.Router;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException, CloneNotSupportedException {
    	int port = args.length > 0 ? Integer.parseInt(args[0]) : AppConfig.DEFAULT_PORT;
    	String servedDirectory = args.length > 1 ? args[1] : AppConfig.DIRECTORY_ROOT;

    	Router router = RouterConfig.createStaticFileRouter(servedDirectory);

        HttpServer server = new HttpServer(port, router);
        server.run();
    }
}

