import java.io.IOException;
import server.HttpServer;
import utils.AppConfig;
import webapp.WebApp;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) throws IOException {
    	int port = args.length > 0 ? Integer.parseInt(args[0]) : AppConfig.DEFAULT_PORT;
    	String servedDirectory = args.length > 1 ? args[1] : AppConfig.DIRECTORY_ROOT;

        HttpServer server = new HttpServer(port);
        WebApp webApp = new WebApp(server);
        webApp.bootingUpServer();
    }
}

