import java.io.IOException;
import server.ThreadPoolServer;
import utils.AppConfig;
import utils.HttpClient;
import utils.DBUtil;
import webapp.WebApp;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) throws IOException {
    	int port = args.length > 0 ? Integer.parseInt(args[0]) : AppConfig.DEFAULT_PORT;
    	String servedDirectory = args.length > 1 ? args[1] : AppConfig.DIRECTORY_ROOT;
        int amountThread = args.length > 2 ? Integer.parseInt(args[2]) : AppConfig.AMOUNT_THREAD;

        DBUtil.setupDatabase();
        ThreadPoolServer server = new ThreadPoolServer(port, amountThread);
        WebApp webApp = new WebApp(server);
        webApp.bootingUpServer();

        
    }
}

